#!/bin/bash
# ============================================
# Ansible MCP Server - Installation Script
# ============================================
# This script automates the installation process
# Run with: chmod +x install.sh && ./install.sh
# ============================================

# Source common functions
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/common.sh"

print_banner "Installation"

# ===== Check Prerequisites =====
check_prerequisites || exit 1

echo ""

# ===== Create Directories =====
log_info "Creating directories..."
mkdir -p "$PROJECT_DIR/playbooks" \
         "$PROJECT_DIR/inventory" \
         "$PROJECT_DIR/logs" \
         "$PROJECT_DIR/templates" \
         "$SRC_DIR/vault/config"
log_success "Created: playbooks, inventory, logs, templates, vault/config"

# ===== Create Inventory =====
if [ ! -f "$PROJECT_DIR/inventory/hosts" ]; then
    cat > "$PROJECT_DIR/inventory/hosts" << 'EOF'
[local]
localhost ansible_connection=local

[webservers]
# Add your servers here
# web1.example.com ansible_user=admin

[databases]
# db1.example.com ansible_user=admin
EOF
    log_success "Created default inventory file"
else
    log_warn "Inventory file exists, skipping"
fi

# ===== Create Environment File =====
echo ""
log_info "Setting up environment..."

if [ ! -f "$ENV_FILE" ]; then
    # Generate JWT secret
    JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)

    cat > "$ENV_FILE" << EOF
# Generated by install.sh on $(date)

# ===== REQUIRED =====
JWT_SECRET=${JWT_SECRET}
POSTGRES_PASSWORD=ansible_mcp_$(openssl rand -hex 8 2>/dev/null || head -c 8 /dev/urandom | xxd -p)
POSTGRES_USER=ansible_mcp
POSTGRES_DB=awx
WEB_DB_NAME=ansible_mcp

# ===== SECURITY =====
VAULT_ROOT_TOKEN=dev-token-$(openssl rand -hex 8 2>/dev/null || head -c 8 /dev/urandom | xxd -p)
AWX_SECRET_KEY=$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p)
GITLAB_ROOT_PASSWORD=gitlab-$(openssl rand -hex 8 2>/dev/null || head -c 8 /dev/urandom | xxd -p)
GRAFANA_ADMIN_PASSWORD=grafana-$(openssl rand -hex 8 2>/dev/null || head -c 8 /dev/urandom | xxd -p)

# ===== AI PROVIDER =====
# Uncomment and set your API key
AI_PROVIDER=openai
AI_MODEL=gpt-4
# OPENAI_API_KEY=sk-your-key-here
# ANTHROPIC_API_KEY=your-key-here
# GEMINI_API_KEY=your-key-here

# ===== LOGGING =====
LOG_LEVEL=info
EOF

    log_success "Created .env with generated secrets"
    log_warn "IMPORTANT: Add your AI API key to .env"
else
    log_warn ".env file exists, skipping"
fi

# Validate configuration
validate_env || {
    log_error "Configuration validation failed"
    echo "Please check your .env file"
    exit 1
}

# ===== Select Installation Type =====
echo ""
echo "Select installation type:"
echo "  1) Minimal (MCP + AI + Redis + Vault + Postgres) - ~1GB RAM"
echo "  2) Standard (+ Web UI + Prometheus + Grafana) - ~2GB RAM"
echo "  3) Full (+ GitLab) - ~8GB RAM"
echo ""
read -p "Enter choice [1-3, default: 2]: " INSTALL_TYPE
INSTALL_TYPE=${INSTALL_TYPE:-2}

# Get services for selected type
BUILD_SERVICES=$(get_build_services_for_type "$INSTALL_TYPE")
RUN_SERVICES=$(get_services_for_type "$INSTALL_TYPE")

case ${INSTALL_TYPE} in
    1) log_info "Selected: Minimal installation" ;;
    2) log_info "Selected: Standard installation" ;;
    3) log_info "Selected: Full installation" ;;
    *)
        log_warn "Invalid choice, using standard..."
        INSTALL_TYPE=2
        BUILD_SERVICES=$(get_build_services_for_type 2)
        RUN_SERVICES=$(get_services_for_type 2)
        ;;
esac

# ===== Pull Docker Images =====
echo ""
log_info "Pulling base Docker images..."
docker_compose pull redis vault postgres prometheus grafana 2>/dev/null || true
log_success "Base images pulled"

# ===== Build Custom Images =====
echo ""
log_info "Building custom images (parallel build)..."
log_warn "First build may take 5-10 minutes..."

if ! docker_compose build --parallel $BUILD_SERVICES; then
    log_error "Build failed!"
    echo ""
    echo "Troubleshooting:"
    echo "  1. Check Docker disk space: docker system df"
    echo "  2. Check build logs above for errors"
    echo "  3. Try building individually: docker compose build ansible-mcp"
    exit 1
fi

log_success "Images built successfully"

# ===== Start Services =====
echo ""
log_info "Starting services..."

if [ -z "$RUN_SERVICES" ]; then
    log_info "Starting full stack..."
    docker_compose up -d
else
    log_info "Starting selected services..."
    docker_compose up -d $RUN_SERVICES
fi

# ===== Wait for Services =====
echo ""
log_info "Waiting for services to become healthy..."

# Wait for core infrastructure first
wait_for_health "Redis" 6379 "" 30 || log_warn "Redis may still be starting"
wait_for_health "PostgreSQL" 5432 "" 30 || log_warn "PostgreSQL may still be starting"
wait_for_health "Vault" 8200 "/v1/sys/health" 30 || log_warn "Vault may still be starting"

# Wait for application services
wait_for_health "MCP Server" 3000 "/health" 60 || log_warn "MCP Server may still be starting"
wait_for_health "AI Generator" 8000 "/health" 60 || log_warn "AI Generator may still be starting"

if [ "$INSTALL_TYPE" -ge 2 ] 2>/dev/null; then
    wait_for_health "Web UI" 3001 "/api/health" 60 || log_warn "Web UI may still be starting"
fi

# ===== Verify Installation =====
echo ""
log_info "Verifying installation..."
check_all_services

# ===== Print Summary =====
print_banner "Installation Complete!"

echo "Services:"
docker_compose ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || docker_compose ps

print_urls "$INSTALL_TYPE"

echo "Next steps:"
echo "  1. Add your AI API key to .env"
echo "  2. Run: docker compose restart ansible-mcp"
echo "  3. Test: curl http://localhost:3000/health"
echo "  4. Read docs/quickstart.md"
echo ""
echo -e "${GREEN}Enjoy using Ansible MCP Server!${NC}"
